const fs=require('node:fs'),path=require('node:path');
const root=__dirname;
global.window={};require('./content-data.js');const D=window.CareContent;const C=require('./product-core.js');
const E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fs.mkdirSync(path.join(root,'downloads'),{recursive:true});
for(const [id,title] of [['offer','Customer offer'],['business','Business model'],['outreach','Outreach lab'],['presentation','Classroom kit']]){
 fs.writeFileSync(path.join(root,id+'.html'),'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+' · Sliver Care</title><link rel="stylesheet" href="product.css"></head><body data-page="'+id+'"><div id="product-shell"></div><main class="product-main" id="content"><div id="page-body"></div></main><div id="product-footer"></div><script src="product-core.js"></script><script src="product-common.js"></script><script src="content-data.js"></script><script src="content-pages.js"></script></body></html>');
}
const sections=[
 {title:'Executive summary',paragraphs:['Sliver Care is an offline family-care coordination MVP. It supports the sequence reminder → self-reported response or help request → family follow-up → recorded outcome. The intended buyer is the adult child coordinating care for an independently living parent. The product’s proposed paid value is organisation and reporting, with AI as an optional assistant rather than the core reason to pay.','This edition implements local profiles, schedules, assignments, reports and Pro handover/rota. Payment and AI are explicitly simulated. No live cloud service, emergency response, real customer base, actual revenue or validated demand is claimed.']},
 {title:'Problem, users and buyer',paragraphs:['The problem hypothesis is that reminders do not by themselves resolve uncertainty or establish responsibility. Family members may not know whether a response was received, who should follow up, or what happened after contact.','Initial segment: adult children coordinating care for older relatives who live independently and can use the response interface. A participating family must have someone available to follow up. The older adult and family caregiver are users; the coordinating adult child is the proposed buyer. This target hypothesis still requires real interviews and offers.']},
 {title:'Product scope and working value',bullets:['Free: one demo recipient and caregiver, one editable reminder plan, responses, help requests, manual follow-up, notes and accessible local history.','Plus: up to two recipients and four family roles, multiple schedules, responsibility assignment, weekly summaries and downloadable text reports.','Pro: up to five recipients and eight roles, cross-recipient overview, responsible-person filtering, backup responsibility, configurable follow-up stages, dated duty rota and recorded handovers.','Pro 5x and 20x have identical care features. Their monthly AI simulation allowances are 100 and 400, compared with Plus 20.','Core care remains usable if AI allowance is exhausted. Downgrading preserves records and profiles, with creation limits governed by the active tier.'],paragraphs:['The report feature is a tangible output: it computes the number of started care items, self-reported check-ins, recorded follow-ups, outstanding items and help requests from the saved demo data. It includes actual entered notes. A Pro report adds recipient overview, daily activity counts and handover records. Daily activity reflects the dates of recorded events; it is not a clinical adherence measure.','Capacity limits are product defaults for this offline edition, not validated market-optimal limits.']},
 {title:'State meanings and honest boundaries',bullets:['A check-in records a self-report; it does not verify medication intake.','A resolved care item records a family action and note; it does not establish clinical safety.','No response means the demo has no recorded response, not proof of illness or missed medication.','A help request updates the local page only. It does not contact family, volunteers or emergency services.','The original two-phone guided example and the working household are separate demo contexts, explicitly labelled.','The demo clock advances only through controls. It does not schedule background work after closing the page.','Local storage is not a secure cloud account or backup service. Use fictional care data and export backups.']},
 {title:'Pricing and subscription mechanics',table:{headers:['Plan','Monthly / RMB','Annual total / RMB','Demo capacity','Monthly AI simulation'],rows:Object.values(C.PLANS).map(p=>[p.name,p.month,p.year,p.recipients+' recipient'+(p.recipients===1?'':'s')+' / '+p.caregivers+' family role'+(p.caregivers===1?'':'s'),p.ai])},paragraphs:['Annual prices are paid once, not charged at the displayed monthly equivalent. The annual equivalents are Plus ¥32.50/month, Pro 5x approximately ¥65.83/month and Pro 20x ¥82.50/month. Monthly and annual options have the same functionality and monthly AI limits.','The checkout quotes the selected total, but the actual charge is always zero. Success activates local features; failure and cancellation preserve the current plan. Duplicate order completion is ignored. A demo receipt is labelled as simulated, not proof of payment.','AI simulation usage persists when switching plans and is reset only through the explicit demo cycle control. Historical results remain visible. This is a classroom cycle model, not a running billing engine.']},
 {title:'Commercial offer and acquisition approach',paragraphs:[D.offer.invitation,D.offer.quoteNote,'The first acquisition experiment is a specific offer to evaluate a relevant scenario, not a generic satisfaction survey. Start with family caregivers and use community organisations as potential feedback or introduction channels, without implying a secured partnership.'],bullets:['Before contact: choose a relevant target, customise the problem statement and quote the correct proposed price.','During contact: show one usable workflow and ask for a specific next step.','After contact: record actual date/time, target, offer, response and experience. Retain evidence and a respectful follow-up plan.','Do not promise connected delivery, medical monitoring or paid services that the offline edition cannot deliver.']},
 {title:'Business model and economics',paragraphs:['Revenue hypothesis: optional family subscriptions, paid by the organising adult child. Value is coordination, shared responsibility, follow-up records and reports. Proposed channels are caregiver communities, family referrals, educational content and possible community pilots.','Key activities are usable product development, customer discovery, reliability testing and support. Resources include the MVP, engineering and design capability and consenting future pilot families. Potential partners are community and infrastructure organisations; none are claimed as contracted.','The interactive economics sandbox uses an illustrative plan mix of 70% Plus, 20% Pro 5x and 10% Pro 20x, with 60% monthly and 40% annual billing. This yields approximately ¥49.47 monthly revenue per paying family. With assumed paid-family service/support/AI cost ¥12, a 5:1 free-to-paid ratio at ¥0.50 per free family, a 1% processing allowance, 4% equivalent monthly churn and ¥80 acquisition cost, contribution after replacement acquisition is approximately ¥31.27 per paid family.','At assumed fixed operations of ¥30,000/month, this model reaches break-even at approximately 960 paid families. At 800 paid families, the modelled monthly result is approximately −¥4,982.40. These are steady-state scenarios, not an estimate of the cost or time to acquire those families. Taxes, financing and launch costs are excluded.','All cost and behaviour inputs are assumptions, not quotes, observed customers or audited financial results. The previous single-Plus financial model remains historical and should not be presented as proof of multi-tier viability.']},
 {title:'Outreach: evidence versus rehearsal',paragraphs:['Real outreach has been explicitly deferred by the project owner. The product provides a separate actual-outreach log that starts empty and ten fictional response scenarios for rehearsal. The scenarios consist of six family situations and four fictional organisations. They have no invented real identity, contact address or outreach timestamp.','Fictional scenarios include four positive responses, four negative responses and two no-response situations. Those numbers describe authored practice material only. They are not research findings, conversion rates or completion of the course quota.','The course announcement requests at least ten commercial offers to people or organisations, logging the target, date/time, offer, outcome and experience/notes. Completing that requirement needs actual authorised contact and genuine records. The local log cannot verify a contact happened.'],bullets:['Record the proposed price and requested action in each actual offer.','Keep evidence references and actual responses, including rejection and silence.','Do not count repeated drafts, fictional cases or generated replies as real contacts.']},
 {title:'Demonstration and validation',bullets:['Start a Free reminder, request help and record the family’s outcome.','Show the report feature is gated, while basic care history remains readable.','Demonstrate simulated failure/cancellation, then successful Plus activation.','Download the report and locate the note you just entered.','Add a second recipient and caregiver; start an assigned reminder.','Activate Pro, demonstrate a backup taking responsibility after the configured delay, then save a handover.','Generate an input-grounded template and show the used allowance. Demonstrate that failure/cancellation does not consume it.','Show the empty actual log next to the clearly labelled fictional scenarios.'],paragraphs:['Validation must check both runtime behaviour and content claims. A passing code check alone cannot prove usability, customer demand, clinical value or commercial viability.']},
 {title:'Limitations and next evidence',bullets:['Required before live connected service: accounts, cross-device state, actual notification delivery, access controls, recovery, support and agreed customer terms.','Required for market evidence: authorised actual offers, documented acceptance/rejection reasons, price evaluation, repeat-use observations and measured service costs.','Required for the final course submission: the separate rubric, report format, presentation length and calendar deadline. Those materials were not supplied.','The individual class quiz requires the actual course slides and class content; this product package cannot establish readiness for that quiz.','No GitHub deployment, real billing, external message or Blackboard submission is part of this offline package.']},
 {title:'Conclusion',paragraphs:['The offline product provides an inspectable local workflow and a working commercial-feature demonstration with clear pricing. The accompanying customer offer, outreach tools and classroom materials make the business proposition explainable. The remaining real-world evidence must come from genuine contact and a reliable connected pilot; it cannot be replaced by polished visuals or fictional replies.']}
];
const report={title:'Sliver Care Product and Commercialisation Report',subtitle:'Offline classroom edition · prepared draft · real outreach deferred',sections};
fs.writeFileSync(path.join(root,'downloads','report-content.json'),JSON.stringify(report,null,2));
let md='# '+report.title+'\n\n'+report.subtitle+'\n\n';
for(const s of sections){md+='## '+s.title+'\n\n';for(const p of s.paragraphs||[])md+=p+'\n\n';for(const b of s.bullets||[])md+='- '+b+'\n';if(s.bullets)md+='\n';if(s.table){md+='| '+s.table.headers.join(' | ')+' |\n| '+s.table.headers.map(()=> '---').join(' | ')+' |\n';for(const row of s.table.rows)md+='| '+row.join(' | ')+' |\n';md+='\n';}}
fs.writeFileSync(path.join(root,'downloads','Sliver_Care_Report.md'),md);
const reportHtml=sections.map(s=>'<section class="section"><h2>'+E(s.title)+'</h2>'+(s.paragraphs||[]).map(p=>'<p>'+E(p)+'</p>').join('')+(s.bullets?'<ul>'+s.bullets.map(b=>'<li>'+E(b)+'</li>').join('')+'</ul>':'')+(s.table?'<div class="table-wrap"><table><thead><tr>'+s.table.headers.map(h=>'<th>'+E(h)+'</th>').join('')+'</tr></thead><tbody>'+s.table.rows.map(r=>'<tr>'+r.map(v=>'<td>'+E(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'')+'</section>').join('');
fs.writeFileSync(path.join(root,'report.html'),'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Project report · Sliver Care</title><link rel="stylesheet" href="product.css"></head><body data-page="presentation"><div id="product-shell"></div><main id="content" class="product-main"><div class="page-intro"><p class="eyebrow">PROJECT REPORT / 项目报告</p><h1>'+E(report.title)+'</h1><p class="lead">'+E(report.subtitle)+'</p><div class="actions"><button onclick="window.print()">Print / save as PDF</button><a class="button secondary" href="downloads/Sliver_Care_Report.docx" download>Download Word report</a><a class="button secondary" href="downloads/Sliver_Care_Report.md" download>Download text source</a><a class="button secondary" href="presentation.html">Presentation</a></div></div>'+reportHtml+'</main><div id="product-footer"></div><script src="product-core.js"></script><script src="product-common.js"></script></body></html>');
fs.writeFileSync(path.join(root,'downloads','Sliver_Care_Offer.txt'),['SLIVER CARE — PROPOSED CUSTOMER OFFER','FREE OFFLINE EVALUATION · NO CHARGE','',D.offer.invitation,'',D.offer.quoteNote,'',D.offer.nextStep].join('\n'));
fs.writeFileSync(path.join(root,'downloads','FICTIONAL_Outreach_Rehearsal.json'),JSON.stringify({status:'FICTIONAL — NOT CUSTOMER EVIDENCE',countsTowardRealOutreach:false,scenarios:D.simulations},null,2));
console.log('Built offer, business, outreach, presentation and report pages plus editable content sources.');
