(function(){
 'use strict';
 const P=Product,C=P.C,E=P.esc,$=s=>document.querySelector(s),area=$('#workspace-content'),dialog=$('#work-dialog');
 let section='desk',recipientFilter='all',ownerFilter='all',reportDays=7,pending=null,lastFocus=null;
 const names=(collection,id)=>P.state[collection].find(x=>x.id===id)?.name||'Unassigned';
 const option=(id,label,selected)=>'<option value="'+E(id)+'"'+(id===selected?' selected':'')+'>'+E(label)+'</option>';
 const opts=(collection,selected,all=false)=>(all?option('all','All '+collection,selected):'')+P.state[collection].map(x=>option(x.id,x.name,selected)).join('');
 const button=(action,label,attrs='',secondary=true)=>'<button type="button" data-action="'+action+'" '+attrs+' class="'+(secondary?'secondary':'')+'">'+label+'</button>';
 const heading=(title,note)=>'<h2 tabindex="-1" id="pane-title">'+title+'</h2><p class="muted">'+note+'</p>';
 const formInput=(label,name,value='',type='text',extra='')=>'<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+E(value)+'" '+extra+'></label>';
 function message(text,error=false){$('#message').textContent=text;$('#message').classList.toggle('error',error);}
 function commit(fn,note){try{const result=P.transact(fn);render();if(note)message(note);return result;}catch(e){message(e.message,true);return null;}}
 function modal(title,body){lastFocus=document.activeElement;$('#dialog-content').innerHTML='<h2 id="dialog-title">'+title+'</h2>'+body;if(!dialog.open)dialog.showModal();}
 dialog.addEventListener('close',()=>{pending=null;if(lastFocus?.isConnected)lastFocus.focus();});
 function quota(){return Math.max(0,C.plan(P.state).ai-P.state.subscription.used);}
 function desk(){
  const s=P.state,m=C.metrics(s),isPro=C.plan(s).rank===2;
  const items=s.cases.filter(c=>(recipientFilter==='all'||c.recipientId===recipientFilter)&&(ownerFilter==='all'||c.ownerId===ownerFilter)).slice().reverse();
  return heading('The care desk','Start a reminder or advance the demo clock. A response and a family follow-up are different records.')+
   '<div class="actions">'+button('advance','Time +15 min','data-minutes="15"')+button('advance','Time +30 min','data-minutes="30"')+button('advance','Next demo day','data-minutes="1440"')+'</div><div class="stat-grid">'+[['Started',m.started],['Self-reported',m.confirmed],['Follow-up recorded',m.resolved],['Open',m.open]].map(([label,value])=>'<div class="stat"><strong>'+value+'</strong><span>'+label+' · '+(label==='Open'?'all saved dates':'last 7 demo days')+'</span></div>').join('')+'</div>'+
   '<div class="form-grid"><label>Care recipient<select id="recipient-filter">'+opts('recipients',recipientFilter,true)+'</select></label><label>Responsible caregiver'+(isPro?'':' · Pro filter')+'<select id="owner-filter" '+(!isPro?'disabled':'')+'>'+opts('caregivers',ownerFilter,true)+'</select></label></div>'+
   '<div class="section"><h3>Reminder plans</h3><div class="table-wrap"><table><thead><tr><th>Recipient / reminder</th><th>Time</th><th>Responsible</th><th>Action</th></tr></thead><tbody>'+s.schedules.map((t,i)=>'<tr><td>'+E(names('recipients',t.recipientId))+'<br><strong>'+E(t.title)+'</strong></td><td>'+E(t.time)+'</td><td>'+E(names('caregivers',t.ownerId))+'</td><td>'+button('start','Start now','data-id="'+E(t.id)+'" '+(s.cases.some(c=>c.scheduleId===t.id&&C.OPEN.includes(c.status))||(C.plan(s).rank===0&&i>0)?'disabled':''))+'</td></tr>').join('')+'</tbody></table></div></div>'+
   '<div class="section"><h3>Care items</h3>'+(items.length?'<div class="grid">'+items.map(c=>'<article class="panel case" data-status="'+c.status+'"><div class="case-top"><span class="tag">'+E(names('recipients',c.recipientId))+'</span><span class="tag">'+E(C.STATUS[c.status])+'</span></div><h3>'+E(c.title)+'</h3><p>Responsible: <strong>'+E(names('caregivers',c.ownerId))+'</strong><br>Started: '+new Date(c.dueAt).toISOString().slice(0,16).replace('T',' ')+'<br>Follow-up stages: '+c.remindAfter+' / '+c.followAfter+' minutes</p><div class="actions">'+(['waiting','reminded'].includes(c.status)?button('confirm','Check in','data-id="'+c.id+'"',false):'')+(C.OPEN.includes(c.status)?button('help','Request help','data-id="'+c.id+'"')+button('resolve','Record outcome','data-id="'+c.id+'"'):'')+button('note','Add note','data-id="'+c.id+'"')+(isPro&&C.OPEN.includes(c.status)?button('handover','Hand over','data-id="'+c.id+'"'):'')+'</div></article>').join('')+'</div>':'<div class="empty">No items match this view. Use “Start now” to begin a care flow.</div>')+'</div>'+(isPro?'<div class="section"><h3>Pro overview</h3>'+s.recipients.map(r=>{const n=C.metrics(s,r.id);return '<p><strong>'+E(r.name)+'</strong> — '+n.open+' open (all dates); 7-day activity: '+n.confirmed+' check-ins, '+n.resolved+' follow-up outcomes.</p>';}).join('')+'</div>':'');
 }
 function household(){const s=P.state,p=C.plan(s);return heading('Your demo household','Use fictional names. These are local roles, not invited users or connected accounts.')+'<div class="grid"><section class="panel"><span class="tag">'+s.recipients.length+' / '+p.recipients+' demo capacity</span><h3>Care recipients</h3>'+s.recipients.map(r=>'<p><strong>'+E(r.name)+'</strong><br><small>'+E(r.context)+'</small></p>').join('')+'<form data-form="recipient" class="form-grid">'+formInput('Name','name','','text','required maxlength="60"')+formInput('Context','context','','text','maxlength="160"')+'<button '+(s.recipients.length>=p.recipients?'disabled':'')+'>Add recipient</button></form></section><section class="panel"><span class="tag">'+s.caregivers.length+' / '+p.caregivers+' demo capacity</span><h3>Family caregivers</h3>'+s.caregivers.map(g=>'<p><strong>'+E(g.name)+'</strong><br><small>'+E(g.role)+'</small></p>').join('')+'<form data-form="caregiver" class="form-grid">'+formInput('Name','name','','text','required maxlength="60"')+formInput('Family role','role','','text','maxlength="80"')+'<button '+(s.caregivers.length>=p.caregivers?'disabled':'')+'>Add caregiver</button></form></section></div><p class="notice">Capacity limits are defaults for this classroom edition. Downgrading retains all existing profiles and records; additional creation is limited by the selected plan.</p>';}
 function schedules(){const s=P.state,isPro=C.plan(s).rank===2;return heading('Reminder plans & responsibility','Choose a routine, a time and a responsible person. Pro adds a backup, configurable follow-up timing and a dated rota.')+button('new-schedule','Add reminder plan','',false)+'<div class="table-wrap section"><table><thead><tr><th>Reminder</th><th>Owner / backup</th><th>Timing</th><th></th></tr></thead><tbody>'+s.schedules.map(t=>'<tr><td>'+E(t.title)+'<br><small>'+E(names('recipients',t.recipientId))+' · '+t.time+'</small></td><td>'+E(names('caregivers',t.ownerId))+'<br><small>Backup: '+E(t.backupId?names('caregivers',t.backupId):'None')+'</small></td><td>'+t.remindAfter+' / '+t.followAfter+' min</td><td>'+button('edit-schedule','Edit','data-id="'+t.id+'"')+'</td></tr>').join('')+'</tbody></table></div><p class="notice">Free and Plus run 30/60-minute stages. Pro timing applies when a new care item starts. A rota applies to new items on its demo date; it does not silently reassign existing cases.</p><section class="panel section"><span class="tag pro">PRO</span><h3>Duty rota</h3>'+(isPro?'<form data-form="rota" class="form-grid"><label>Recipient<select name="recipientId">'+opts('recipients')+'</select></label><label>Caregiver<select name="caregiverId">'+opts('caregivers')+'</select></label>'+formInput('Demo date','day',new Date(s.clock).toISOString().slice(0,10),'date','required')+'<button>Save duty</button></form>':'<p>Activate a Pro demo to assign duty by recipient and day.</p><a class="button" href="#account">View demo plans</a>')+s.rota.map(r=>'<p>'+E(r.day)+' · '+E(names('recipients',r.recipientId))+' → '+E(names('caregivers',r.caregiverId))+'</p>').join('')+'</section><section class="section"><h3>Handover record</h3>'+(s.handovers.map(h=>'<p>'+E(names('caregivers',h.fromId))+' → '+E(names('caregivers',h.toId))+': '+E(h.note)+'</p>').join('')||'<p class="muted">No handovers yet. Use “Hand over” on an open item in the care desk.</p>')+'</section>';}
 function scheduleDialog(t={}){const isPro=C.plan(P.state).rank===2;modal(t.id?'Edit reminder':'New reminder','<form data-form="schedule" class="form-grid"><input type="hidden" name="id" value="'+E(t.id||'')+'">'+formInput('Reminder title','title',t.title||'','','required maxlength="80"')+formInput('Daily demo time','time',t.time||'09:00','time','required')+'<label>Recipient<select name="recipientId">'+opts('recipients',t.recipientId)+'</select></label><label>Responsible caregiver<select name="ownerId">'+opts('caregivers',t.ownerId)+'</select></label><label>Backup caregiver · Pro<select name="backupId" '+(!isPro?'disabled':'')+'>'+option('','No backup',t.backupId)+opts('caregivers',t.backupId)+'</select></label><span></span>'+formInput('Reminder after (minutes) · Pro','remindAfter',isPro?(t.remindAfter||30):30,'number','min="5" max="120" required '+(!isPro?'disabled':''))+formInput('Family follow-up after · Pro','followAfter',isPro?(t.followAfter||60):60,'number','min="6" max="240" required '+(!isPro?'disabled':''))+'<p class="field-help full">These are elapsed minutes after the reminder starts. No notification runs while the page is closed.</p><button>Save reminder</button></form>');}
 function reports(){const s=P.state,m=C.metrics(s,recipientFilter,reportDays),paid=C.plan(s).rank>0;let body='';if(paid)body='<pre id="report-preview">'+E(C.report(s,recipientFilter,reportDays))+'</pre>';else body='<div class="empty">A downloadable care summary is the working paid feature. Activate Plus or Pro in the simulated checkout to generate it from your actual demo events. Your basic history remains visible below.</div>';return heading('A report worth keeping','Activity counts use the selected period. Open items include earlier dates. Report generation uses no AI allowance.')+'<div class="form-grid"><label>Recipient<select id="report-recipient">'+opts('recipients',recipientFilter,true)+'</select></label><label>Reporting period<select id="report-days">'+[1,7,30].map(d=>option(String(d),d+' demo day'+(d===1?'':'s'),String(reportDays))).join('')+'</select></label></div><div class="actions">'+button('download-report','Download care report (.txt)',paid?'':'disabled',false)+button('download-events','Export raw event data (.json)')+'</div><div class="section">'+body+'</div><h3 class="section">Saved event history</h3><div class="table-wrap"><table><thead><tr><th>Demo time</th><th>Recipient</th><th>Record</th></tr></thead><tbody>'+m.events.slice().reverse().map(e=>'<tr><td>'+new Date(e.at).toISOString().slice(0,16).replace('T',' ')+'</td><td>'+E(names('recipients',e.recipientId))+'</td><td>'+(e.caseId?'<strong>'+E(s.cases.find(c=>c.id===e.caseId)?.title||'Care item')+'</strong><br>':'')+E(e.note)+'</td></tr>').join('')+'</tbody></table></div>'+(m.events.length?'':'<p>No events in this period.</p>');}
 function assistant(){const s=P.state,p=C.plan(s);return heading('Assistant lab','Local templates organise your demo records. No live model is connected; review drafts before use.')+'<div class="notice"><strong>AI SIMULATION</strong> · Cycle '+s.subscription.cycle+' · '+s.subscription.used+' used / '+p.ai+' monthly allowance · '+quota()+' remaining. One saved successful draft = one use, including regeneration. Failed, cancelled or invalid requests use zero. All family roles share this allowance. No rollover; viewing or saving existing drafts is free.</div><form data-form="ai" class="panel form-grid"><label>Recipient<select name="recipientId">'+opts('recipients')+'</select></label><label>Task<select name="kind"><option value="summary">Weekly care summary</option><option value="handover">Handover draft & open items</option><option value="message">Caring message</option></select></label><label class="full">Optional fictional context<textarea name="background" maxlength="400"></textarea></label><label>Simulation outcome<select name="outcome"><option value="success">Success</option><option value="failure">Failure — no allowance used</option><option value="cancel">Cancel — no allowance used</option></select></label><button '+(p.rank===0?'disabled':'')+'>Generate local draft</button></form>'+(p.rank===0?'<p class="notice">Free: fixed example — “Hello Margaret, please let us know when you have a moment.” Activate Plus or Pro for input-based template generation.</p>':'')+'<div class="section"><h3>Generated drafts</h3>'+s.aiResults.slice().reverse().map(a=>'<details><summary>'+E(names('recipients',a.recipientId))+' / '+E(a.kind)+' / cycle '+a.cycle+'</summary><pre>'+E(a.text)+'</pre>'+button('save-draft',s.drafts.some(d=>d.resultId===a.id)?'Draft saved':'Review complete — save draft','data-id="'+a.id+'" '+(s.drafts.some(d=>d.resultId===a.id)?'disabled':''))+'</details>').join('')+'</div>';}
 function account(){const s=P.state;return heading('Choose a demo subscription','No charge. The selected plan changes the features available in this local workspace. This is not a real subscription.')+'<div class="grid three">'+Object.values(C.PLANS).filter(p=>p.rank>0).map(p=>'<article class="panel '+(p.rank===2?'dark':'')+'"><span class="tag '+(p.rank===2?'pro':'')+'">'+window.CarePlanValue.copy[p.id].title+'</span><h3>'+p.name+'</h3><p class="price-large">¥'+p.month+'<small>/month</small></p><p class="muted">or ¥'+p.year+'/year, paid once</p><p>'+window.CarePlanValue.copy[p.id].who+' '+window.CarePlanValue.copy[p.id].extra+'</p><p>'+p.recipients+' recipients · '+p.caregivers+' family roles<br>'+p.ai+' AI simulations per monthly cycle</p><div class="actions">'+button('checkout','Monthly demo','data-plan="'+p.id+'" data-billing="month"',false)+button('checkout','Annual demo','data-plan="'+p.id+'" data-billing="year"',false)+'</div></article>').join('')+'</div><p class="notice">Pro 5x adds rota, backup responsibility and handovers to Plus. Pro 20x costs ¥20 more per month for 300 extra generations; its care features and model quality stay the same. Annual totals equal ten monthly fees, paid upfront in the proposal; allowance stays monthly. Evaluation charges ¥0. Cross-device sync, remote notifications and live AI are proposed, with no launch date.</p><div class="actions">'+button('reset-purchase','Return to Free (keep all records)')+'</div><h3 class="section">Simulated receipts</h3>'+s.subscription.orders.slice().reverse().map(o=>'<div class="panel"><strong>'+E(o.id)+' · '+C.PLANS[o.plan].name+'</strong><p>Quoted: ¥'+o.amount+'/'+o.billing+' · Actual charge: ¥0 · Exercise clock: '+new Date(o.at).toISOString().slice(0,16).replace('T',' ')+'</p>'+button('receipt','Download demo receipt','data-id="'+o.id+'"')+'</div>').join('');}
 function checkout(planId,billing){const p=C.PLANS[planId];pending={planId,billing,token:'demo-'+Date.now()+'-'+Math.random().toString(36).slice(2)};modal('Review your simulated order','<span class="tag simulated">CLASSROOM SIMULATION · NO CHARGE</span><h3>'+p.name+'</h3><p class="price-large">¥'+p[billing]+'<small>/'+billing+'</small></p><p>'+(billing==='year'?'Quoted annual total, paid once. Monthly equivalent: ¥'+(p.year/12).toFixed(2)+'.':'Quoted monthly total per family.')+'</p><p>Local report export, family planning'+(p.rank===2?', rota and handover':'')+' will be enabled after simulated success.</p><p><strong>Actual charge: ¥0.</strong> No payment credentials, real order, automatic renewal or real refund are involved.</p><p id="checkout-note" role="status"></p><div class="actions">'+button('pay-success','Simulate success','',false)+button('pay-failure','Simulate failure')+button('pay-cancel','Cancel')+'</div>');}
 function tools(){return heading('Demo tools & data','Use the exercise clock and explicit controls. Nothing runs in the background when this page is closed.')+'<div class="grid"><section class="panel"><h3>Monthly allowance cycle</h3><p>Cycle '+P.state.subscription.cycle+' · used '+P.state.subscription.used+'. Advancing a cycle resets only the used AI counter. No carry-over; past results are retained. This manual classroom control does not represent a real subscription renewal.</p>'+button('next-cycle','Advance demo allowance cycle')+'</section><section class="panel"><h3>Keep your work</h3><p>Download a backup before closing. Storage is local to this browser and origin. Use the local server for consistent state across pages.</p>'+button('backup','Download full local backup')+'<label class="section">Restore a product backup<input type="file" id="restore-backup" accept="application/json,.json"></label></section></div><details class="section"><summary>Start a fresh scenario household</summary><p>This starts a new scenario household, resets demo purchases and removes care drafts. Your outreach log and unsent evaluation requests are kept. The original two-phone example is separate. Back up care records first.</p>'+button('reset-all','Review reset')+'</details><section class="section"><h3>Five-minute demo route</h3><ol><li>Start a reminder and request help in Care desk.</li><li>Record the family’s outcome.</li><li>Open Reports; Free shows basic history but report generation is locked.</li><li>Choose Plus, demonstrate failure/cancel, then success.</li><li>Download the computed report, then add a second profile and caregiver.</li><li>Activate Pro, assign a backup or rota and hand over an open item.</li><li>Generate a simulated summary; show the allowance and preserved records.</li></ol></section>';}
 function render(){const s=P.state,p=C.plan(s);section=location.hash.slice(1)||'desk';if(!['desk','household','schedules','reports','assistant','account','tools'].includes(section))section='desk';if(p.rank<2)ownerFilter='all';if(recipientFilter!=='all'&&!s.recipients.some(r=>r.id===recipientFilter))recipientFilter='all';$('#account-status').innerHTML='<div><strong>'+p.name+'</strong><br><small>Local demo plan · cycle '+s.subscription.cycle+' · AI remaining '+quota()+'</small></div><div><strong>'+C.date(s)+'</strong><br><small>Exercise clock · UTC-style display</small></div><a href="#account">Manage demo plan ↗</a>';$('#storage-warning').innerHTML=P.warning?'<p class="notice">'+E(P.warning)+'</p>':'';document.querySelectorAll('.workspace-nav a').forEach(a=>{if(a.hash==='#'+section)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});area.innerHTML=({desk,household,schedules,reports,assistant,account,tools}[section])();}
 document.addEventListener('submit',event=>{const f=event.target.closest('[data-form]');if(!f)return;event.preventDefault();const data=Object.fromEntries(new FormData(f));const kind=f.dataset.form;try{let result;P.transact(s=>{if(kind==='recipient')result=C.addRecipient(s,data.name,data.context);if(kind==='caregiver')result=C.addCaregiver(s,data.name,data.role);if(kind==='schedule')result=C.saveSchedule(s,data);if(kind==='rota')result=C.setRota(s,data.recipientId,data.caregiverId,data.day);if(kind==='care-note')result=C.act(s,data.caseId,data.action,data.note);if(kind==='handover')result=C.handover(s,data.caseId,data.toId,data.note);if(kind==='ai')result=C.generate(s,data.kind,data.recipientId,data.background,data.outcome);});if(dialog.open)dialog.close();render();message(kind==='ai'&&!result?'Simulation '+data.outcome+'. No allowance used.':'Saved locally.');}catch(error){if(dialog.open){let errorNode=$('#dialog-error');if(!errorNode){errorNode=document.createElement('p');errorNode.id='dialog-error';errorNode.className='notice';errorNode.setAttribute('role','alert');$('#dialog-content').append(errorNode);}errorNode.textContent=error.message;}else message(error.message,true);}});
 document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,cid=b.dataset.id;try{
  if(action==='close-dialog')dialog.close();
  if(action==='advance')commit(s=>C.advance(s,Number(b.dataset.minutes)),'Demo time advanced.');
  if(action==='start')commit(s=>C.startCase(s,cid),'Reminder started locally.');
  if(action==='confirm'||action==='help')commit(s=>C.act(s,cid,action),'Care state updated. No real notification was sent.');
  if(action==='note'||action==='resolve')modal(action==='resolve'?'Record the outcome':'Add a note','<form data-form="care-note"><input type="hidden" name="caseId" value="'+E(cid)+'"><input type="hidden" name="action" value="'+action+'"><label>What happened? Use fictional information.<textarea name="note" required maxlength="500"></textarea></label><div class="actions"><button>Save '+(action==='resolve'?'& close care item':'note')+'</button></div></form>');
  if(action==='handover')modal('Hand over responsibility','<form data-form="handover"><input type="hidden" name="caseId" value="'+E(cid)+'"><label>Next responsible caregiver<select name="toId">'+opts('caregivers')+'</select></label><label class="section">Handover context<textarea name="note" required maxlength="500"></textarea></label><div class="actions"><button>Save handover</button></div></form>');
  if(action==='new-schedule')scheduleDialog();if(action==='edit-schedule')scheduleDialog(P.state.schedules.find(t=>t.id===cid));
  if(action==='checkout')checkout(b.dataset.plan,b.dataset.billing);
  if(action==='pay-failure'){if(pending){P.transact(s=>C.activate(s,pending.planId,pending.billing,'failure',pending.token));$('#checkout-note').textContent='Simulated failure. Your plan is unchanged. Retry success or cancel.';}}
  if(action==='pay-cancel'){if(pending)P.transact(s=>C.activate(s,pending.planId,pending.billing,'cancel',pending.token));dialog.close();message('Cancelled. No plan change and no charge.');}
  if(action==='pay-success'&&pending){const order=pending;pending=null;P.transact(s=>C.activate(s,order.planId,order.billing,'success',order.token));dialog.close();render();message('Demo activation complete. Report export and the selected local features are now available.');}
  if(action==='reset-purchase')commit(s=>C.resetPurchase(s),'Returned to Free. Records and this cycle’s used allowance are retained.');
  if(action==='next-cycle')commit(s=>C.nextCycle(s),'New demo cycle. Used AI count reset; past drafts retained.');
  if(action==='save-draft')commit(s=>C.saveDraft(s,cid),'Reviewed draft saved. Nothing was sent.');
  if(action==='download-report')P.download('Sliver-Care-Report.txt',C.report(P.state,recipientFilter,reportDays));
  if(action==='download-events')P.download('Sliver-Care-Events.json',JSON.stringify(C.metrics(P.state,recipientFilter,reportDays).events,null,2),'application/json');
  if(action==='backup')P.download('Sliver-Care-Backup.json',JSON.stringify(P.state,null,2),'application/json');
  if(action==='receipt'){const o=P.state.subscription.orders.find(x=>x.id===cid);P.download('Sliver-Care-Demo-Receipt.txt',['SIMULATED RECEIPT — NOT A PAYMENT RECORD',o.id,C.PLANS[o.plan].name,'Quoted total: ¥'+o.amount+'/'+o.billing,'Actual charge: ¥0','No payment, auto-renewal or account connection.'].join('\n'));}
  if(action==='reset-all')modal('Replace the demo household?','<p>Download a backup first. This replaces care records, demo purchases and care drafts. Your real outreach log and unsent evaluation requests will be kept.</p><div class="actions">'+button('confirm-reset','Replace with a fresh demo','',false)+button('close-dialog','Keep my data')+'</div>');
  if(action==='confirm-reset'){P.transact(s=>C.resetCare(s));dialog.close();render();message('Fresh fictional household ready. Outreach and evaluation requests retained.');}
 }catch(error){message(error.message,true);}});
 document.addEventListener('change',async event=>{const target=event.target;if(target.id==='recipient-filter'||target.id==='report-recipient'){recipientFilter=target.value;render();}if(target.id==='owner-filter'){ownerFilter=target.value;render();}if(target.id==='report-days'){reportDays=Number(target.value);render();}if(target.id==='restore-backup'&&target.files[0]){try{if(target.files[0].size>5000000)throw new Error('Backup exceeds 5 MB.');const restored=C.validate(JSON.parse(await target.files[0].text()));modal('Restore this backup?','<p>This will replace this package’s current local data with '+restored.recipients.length+' profiles and '+restored.events.length+' events. It also replaces the actual outreach log and unsent evaluation requests. Export your current outreach log and keep a full backup first.</p><div class="actions">'+button('apply-backup','Restore backup','',false)+button('close-dialog','Cancel')+'</div>');$('#dialog-content [data-action="apply-backup"]').addEventListener('click',()=>{P.replace(restored);dialog.close();render();message('Backup restored.');},{once:true});}catch(error){message(error.message,true);}}});
 window.addEventListener('hashchange',()=>{message('');render();$('#pane-title')?.focus({preventScroll:true});});
 render();
 const query=new URLSearchParams(location.search);if(C.PLANS[query.get('plan')]&&query.get('plan')!=='free'){location.hash='account';render();checkout(query.get('plan'),query.get('billing')==='year'?'year':'month');}
})();
